In [12]:
#https://towardsdatascience.com/hypothesis-testing-in-machine-learning-using-python-a0dc89e169ce
#https://towardsdatascience.com/demystifying-hypothesis-testing-with-simple-python-examples-4997ad3c5294

T- Test :- A t-test is a type of inferential statistic which is used to determine if there is a significant difference between the means of two groups which may be related in certain features. It is mostly used when the data sets, like the set of data recorded as outcome from flipping a coin a 100 times, would follow a normal distribution and may have unknown variances. T test is used as a hypothesis testing tool, which allows testing of an assumption applicable to a population.  

T-test has 2 types : 1. one sampled t-test 2. two-sampled t-test.  

One sample t-test : The One Sample t Test determines whether the sample mean is statistically different from a known or hypothesised population mean. The One Sample t Test is a parametric test.    
Example :- you have 10 ages and you are checking whether avg age is 30 or not. (check code below for that using python)

# One sample t-test :

In [9]:
from scipy.stats import ttest_1samp
import numpy as np
ages = np.array([20,25,28,30,35,37,28,32,21,35])
print(ages)
ages_mean = np.mean(ages)
print(ages_mean)

tset,pval = ttest_1samp(ages, 30)
print("p-values",pval)
if pval < 0.05:    # alpha value is 0.05 or 5%
   print(" we are rejecting null hypothesis")
else:
  print("we are accepting null hypothesis")


[20 25 28 30 35 37 28 32 21 35]
29.1
p-values 0.6387193286541082
we are accepting null hypothesis


# Two sampled T-test :

In [11]:
from scipy.stats import ttest_ind
import numpy as np
week1 =  np.array([20,25,28,30,35,37,28,32,21,35])
week2 =  np.array([10,35,18,20,15,27,38,32,21,45])
print(week1)
print("week2 data :-\n")
print(week2)
week1_mean = np.mean(week1)
week2_mean = np.mean(week2)
print("week1 mean value:",week1_mean)
print("week2 mean value:",week2_mean)
week1_std = np.std(week1)
week2_std = np.std(week2)
print("week1 std value:",week1_std)
print("week2 std value:",week2_std)
ttest,pval = ttest_ind(week1,week2)
print("p-value",pval)
if pval <0.05:
  print("we reject null hypothesis")
else:
  print("we accept null hypothesis")

[20 25 28 30 35 37 28 32 21 35]
week2 data :-

[10 35 18 20 15 27 38 32 21 45]
week1 mean value: 29.1
week2 mean value: 26.1
week1 std value: 5.5578772926361015
week2 std value: 10.6061303028013
p-value 0.46199497663467726
we accept null hypothesis


# Paired sampled t-test

In [17]:
"""
Paired sampled t-test :- The paired sample t-test is also called dependent sample t-test. 
It’s an uni variate test that tests for a significant difference between 2 related variables.
An example of this is if you where to collect the blood pressure for an individual before and after some treatment,
condition, or time point.
H0 :- means difference between two sample is 0
H1:- mean difference between two sample is not
"""

'\nPaired sampled t-test :- The paired sample t-test is also called dependent sample t-test. \nIt’s an uni variate test that tests for a significant difference between 2 related variables.\nAn example of this is if you where to collect the blood pressure for an individual before and after some treatment,\ncondition, or time point.\nH0 :- means difference between two sample is 0\nH1:- mean difference between two sample is not\n'

In [14]:
import pandas as pd
from scipy import stats
from statsmodels.stats import weightstats as stests

In [16]:
df = pd.read_csv("blood_pressure.csv")

df.head(5)

patient   sex agegrp  bp_before  bp_after
0        1  Male  30-45        143       153
1        2  Male  30-45        163       170
2        3  Male  30-45        153       168
3        4  Male  30-45        153       142
4        5  Male  30-45        146       141

In [18]:
df[['bp_before','bp_after']].describe()

bp_before    bp_after
count  120.000000  120.000000
mean   156.450000  151.358333
std     11.389845   14.177622
min    138.000000  125.000000
25%    147.000000  140.750000
50%    154.500000  149.500000
75%    164.000000  161.000000
max    185.000000  185.000000

In [21]:
ttest,pval = stats.ttest_rel(df['bp_before'], df['bp_after'])
print(pval)

0.0011297914644840823


In [22]:
if pval<0.05:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")

reject null hypothesis
